name: Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install build tools
      run: |
        sudo apt-get install musl-tools

    - name: Download and build dependencies
      run: |
        ./deps-get.sh
        export CC=musl-gcc
        ./deps-build.sh

    - name: Compile project
      run: |
        export CC='musl-gcc -Ideps/usr/include'
        LIBS='deps/usr/lib/libzip.a deps/usr/lib/libexpat.a deps/usr/lib/libhdf5_hl.a deps/usr/lib/libhdf5.a deps/usr/lib/libz.a -ldl -lm -lc' make

    - name: Store compiled binary
      uses: actions/upload-artifact@v2
      with:
        name: h5plexos-linux_x64
        path: h5plexos

  windows:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install build tools
      run: |
        mkdir -p deps
        curl -L https://musl.cc/x86_64-w64-mingw32-cross.tgz | tar xz -C deps

    - name: Download and build dependencies
      run: |
        ./deps-get.sh
        export CC=$(pwd)/deps/x86_64-w64-mingw32-cross/bin/x86_64-w64-mingw32-gcc
        ./deps-build.sh

    - name: Compile project
      run: |
        export CC="$DEPSDIR/x86_64-w64-mingw32-native/bin/x86_64-w64-mingw32-gcc -Ideps/usr/include"
        LIBS='deps/usr/lib/libzip.a deps/usr/lib/libexpat.a deps/usr/lib/libhdf5_hl.a deps/usr/lib/libhdf5.a deps/usr/lib/libz.a -ldl -lm -lc' make

    - name: Store compiled binary
      uses: actions/upload-artifact@v2
      with:
        name: h5plexos-windows_x64
        path: h5plexos.exe

